version: '3'

services:
  memo-client:
    build:
      context: ./client
    command: yarn dev
    container_name: memo-client
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/app
    
  memo-api:
    build:
      context: ./api
    container_name: memo-api
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 8000:80
    volumes:
      - ./api:/var/www/html
  
  memo-db:
    build:
      context: ./database
    container_name: memo-db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGPASSWORD: docker
      POSTGRES_DB: main
      TZ: "Asia/Tokyo"
    ports:
      - 50432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data

  yarn:
    build:
      context: ./client
    entrypoint: yarn
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./client:/home/app

  npm:
    build:
      context: ./client
    entrypoint: npm
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./client:/home/app

  php:
    build:
      context: ./api
    environment:
      TZ: "Asia/Tokyo"
    entrypoint: php
    volumes:
      - ./api:/var/www/html